In [1]:
import numpy as np

In [15]:
a = np.array([1,2,3],dtype= 'uint8')

In [19]:
a[0] = 260

C:\Users\pavel\AppData\Local\Temp\ipykernel_8580\2301436021.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 260 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  a[0] = 260


In [20]:
print(a)

[4 2 3]


In [48]:
a = np.eye(4,dtype= 'uint8')

In [49]:
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=uint8)

In [37]:
a.reshape((1,12))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [50]:
print([elm for elm in a.flat])

[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]


In [64]:
a = np.random.randint(low= 0, high= 100, size = (3,3,3))

In [65]:
print(a,a.min(),a.max())

[[[ 3 40 21]
  [ 9 79 72]
  [80 81  8]]

 [[83 29  4]
  [63 49 29]
  [42 23 23]]

 [[13  6 67]
  [14 10 30]
  [56 18 58]]] 3 83


In [78]:
# 1.14. Create a random vector of size 30 and find the mean value (★☆☆)
# Создайте случайный вектор размером 30 и найдите среднее значение

a = np.random.randint(low= 0, high=30,size=(30))
a.mean()

11.133333333333333

In [169]:
# 2.15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
# Создайте двумерный-массив с 1(единицами) на границе и 0(нулями) внутри

a = np.zeros((4,6),dtype='uint8')

a[0,:] = 1
a[:,0] = 1
a[-1,:] = 1
a[:,-1] = 1

a

3


array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]], dtype=uint8)

In [225]:
# 3.16. How to add a border (filled with 0's) around an existing array? (★☆☆)
# Как добавить границу (заполненную нулями) вокруг существующего массива
#  (например: массив 5 на 5 из единиц окружить нулями, чтобы он превратился в массив 7 на 7?

# a = np.zeros((3,3),dtype='uint8')


# a = np.c_[np.ones(len(a)),a, np.ones(len(a))]
# a = np.r_[[np.ones(len(a[0]))],a,[np.ones(len(a[0]))]]

# np.array(a,dtype= 'int')


row = 3
column = 3

c = np.zeros((row,column),dtype='uint8')

# new_row = row + 2 
# new_colunm = column + 2

# new_c = np.ones((new_row,new_colunm),dtype='uint8')
# new_c[1:-1,1:-1] = c
# print(new_c)

np.pad(c,  pad_width=1, constant_values=1)


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [242]:
# 4.19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
# Создайте матрицу 8x8 и залейте ее шахматным узором Пояснение к заданию: не используйте функцию tile. 
# Ниже будет аналогичное задание 21 с использованием функции tile

def checkerboard(w,h):
    re = np.r_[w * [1,0]]
    ro = np.r_[w * [0,1]]
    return np.array(h*(re,ro))
checkerboard(5,5)

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

In [252]:
# 5.20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
# Рассмотрим массив формы (6,7,8), каков индекс (x, y, z) 100-го элемента?
import numpy as np

shape = (6, 7, 8)
index_of_100th_element = 100

indexes = np.unravel_index(index_of_100th_element, shape)

print(indexes)

(1, 5, 4)


In [274]:
# 6.21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
# Создайте матрицу шахматной доски 8x8, используя функцию tile

re = [1,0]
ro = [0,1]
np.array([re,ro])
shape = (4,4)
np.tile(np.array([re,ro]),shape)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [289]:
# 7.22. Normalize a 5x5 random matrix (★☆☆)
# Нормализовать матрицу случайных значений 5 на 5


matrix = np.random.randint(0,100,size = (5,5))


min_val = np.min(matrix)
max_val = np.max(matrix)

norm_matrix = (matrix - min_val) / (max_val - min_val)
print(matrix)
print()
print(norm_matrix)



[[ 5 63 18 93 81]
 [38 42 98 82 24]
 [57 25 51 26 16]
 [41 59 30 73 59]
 [ 3 84 94 61 96]]

[[0.02105263 0.63157895 0.15789474 0.94736842 0.82105263]
 [0.36842105 0.41052632 1.         0.83157895 0.22105263]
 [0.56842105 0.23157895 0.50526316 0.24210526 0.13684211]
 [0.4        0.58947368 0.28421053 0.73684211 0.58947368]
 [0.         0.85263158 0.95789474 0.61052632 0.97894737]]


In [2]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


In [29]:

# 8.25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
# задан одномерный массив, инвертируйте (поменяйте знак) у всех элементов массива, 
# которые находятся в диапазоне от 3 до 8, прямо в нем самом (без перезаписывания значений).


matrix = np.random.randint(0,10,size = (10))
mask = (matrix >= 3) & (matrix <= 8)
matrix[mask] *= -1
print(matrix)



[-5 -7 -8 -6 -5  1  9  2  9  2]


In [41]:
# 9.30. How to find common values between two arrays? (★☆☆)
# Как найти общие значения между двумя массивами

matrix_1 = np.random.randint(0,5,size = (10))
matrix_2 = np.random.randint(0,5,size = (10))
print(f'matrix_1:{matrix_1}\nmatrix_2:{matrix_2}')

ans = np.intersect1d(matrix_1, matrix_2)
print(ans)


matrix_1:[2 0 0 3 1 3 1 2 0 0]
matrix_2:[0 0 3 4 3 2 2 4 2 3]
[0 2 3]


In [44]:
np.sqrt(-1) == np.emath.sqrt(-1)


C:\Users\pavel\AppData\Local\Temp\ipykernel_13916\2961820512.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [57]:
# 10 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
# Как вычислить ((A + B) * (- A / 2)) на месте 
# (без копирования - то есть без создания дополнительного массива кроме существующих A, B)?

arr1 = np.array([1, 2, 3, 4],dtype='float64')
arr2 = np.array([5, 6, 7, 8],dtype='float64')
arr1 += arr2
arr1 *= (-1/2)

print(arr1)

[-3. -4. -5. -6.]


In [69]:
# 11 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
# Создайте матрицу 5x5 со значениями строк от 0 до 4

shape = (5,1)
a = np.tile(np.arange(0,5),shape)

a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [74]:
# 12 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
# Рассмотрим функцию генератора, которая генерирует 10 целых чисел и использует ее для построения массива.

def generator(n):
    ans = np.random.randint(0, n,size=n)
    return ans
generator(10)

array([4, 1, 7, 7, 5, 7, 7, 8, 9, 6])

In [108]:
# 13 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
# Создайте вектор размера 10 со значениями от 0 до 1, за исключением границ отрезка 0 и 1.


a = np.linspace(0.01,0.99,10)

a

array([0.01      , 0.11888889, 0.22777778, 0.33666667, 0.44555556,
       0.55444444, 0.66333333, 0.77222222, 0.88111111, 0.99      ])

In [110]:
# 14 40. Create a random vector of size 10 and sort it (★★☆)
# Создайте случайный вектор размером 10 и отсортируйте его

ans = sorted(np.random.randint(0, 100,size=10))
print(ans)

[6, 20, 32, 38, 47, 55, 56, 68, 92, 94]


In [113]:
# 15 42. Consider two random array A and B, check if they are equal (★★☆)
# Рассмотрим два случайных массива A и B, проверьте, равны ли они

ans_1 = np.random.randint(0, 100,size=10)
ans_2 = np.random.randint(0, 100,size=10)

answ = np.array_equal(ans_1,ans_2)
answ

False

In [158]:
# 16 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
# Рассмотрим случайную матрицу 10x2, представляющую декартовы координаты, преобразуйте их в полярные координаты.
a = np.random.rand(10, 2) * 10  
x = a[:, 0]
y = a[:, 1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)  

answ = np.column_stack((r, theta))

print(a)
print(answ)


[[0.04665921 0.76052602]
 [5.33707233 3.52844653]
 [1.23959481 3.93000328]
 [7.49898402 2.01113498]
 [8.31146761 9.977062  ]
 [3.03527124 8.57169586]
 [9.0603973  1.78218824]
 [9.77494576 6.82290348]
 [6.31337107 2.04592326]
 [4.84947099 2.56604235]]
[[ 0.76195598  1.5095219 ]
 [ 6.39798999  0.58415293]
 [ 4.12086412  1.26525504]
 [ 7.76398257  0.26202187]
 [12.98546341  0.87622078]
 [ 9.09323052  1.23047013]
 [ 9.23401289  0.19422134]
 [11.92063658  0.60938183]
 [ 6.63659975  0.31338322]
 [ 5.4865237   0.48668585]]


In [209]:
# 17 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
# Создайте случайный вектор размером 10 и замените максимальное значение на 0

a = np.random.randint(1,100,10)
print(a)
index_max_value = np.argmax(a) 
a[index_max_value] = 0

print(a)

[71 87 17 19 89 56 47 98 63 62]
[71 87 17 19 89 56 47  0 63 62]
